-- Add detailed fields to sessions table
ALTER TABLE sessions
ADD COLUMN IF NOT EXISTS session_number INTEGER,
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS audio_url TEXT,
ADD COLUMN IF NOT EXISTS video_url TEXT,
ADD COLUMN IF NOT EXISTS pauta_url TEXT,
ADD COLUMN IF NOT EXISTS ata_url TEXT,
ADD COLUMN IF NOT EXISTS anexo_url TEXT;
